In [24]:
import numpy as np

In [19]:
arr_3d =  np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [20]:
arr = np.array([1.1,2.2, 3.3])
arr_int = arr.astype(np.int32)
print(arr_int)

[1 2 3]


In [21]:
arr = np.array([1,2,3,4, 5, 6])
sliced_arr = arr[1::2]
print(sliced_arr)

[2 4 6]


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9])
new_arr = arr.reshape((3,3))
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Valid Sudoku**

In [28]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [39]:
rows_s = np.sum(s, axis = 1)
for i in rows_s:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku is valid for rows")

Sudoku is valid for rows


In [38]:
columns_s = np.sum(s, axis = 0)
for i in columns_s:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku is valid for columns")

Sudoku is valid for columns


In [50]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        print(s[i:i+3, j:j+3])
        n = s[i:i+3, j:j+3]
        print(n.sum())

[[5 3 4]
 [6 7 2]
 [1 9 8]]
45
[[6 7 8]
 [1 9 5]
 [3 4 2]]
45
[[9 1 2]
 [3 4 8]
 [5 6 7]]
45
[[8 5 9]
 [4 2 6]
 [7 1 3]]
45
[[7 6 1]
 [8 5 3]
 [9 2 4]]
45
[[4 2 3]
 [7 9 1]
 [8 5 6]]
45
[[9 6 1]
 [2 8 7]
 [3 4 5]]
45
[[5 3 7]
 [4 1 9]
 [2 8 6]]
45
[[2 8 4]
 [6 3 5]
 [1 7 9]]
45


**General Questions**

In [103]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [104]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [105]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [106]:
#Extract Math marks of all students.
maths_data = data[:, 1]
maths_data

array([85, 92, 76, 65, 90])

In [107]:
#Find the highest Science mark.
max_science = np.max(data[:,2])
max_science

np.int64(95)

In [108]:
#Get details of the student who scored more than 90 in Math.
math_marks = data[:,1]
marks = math_marks > 90
print(math_marks[marks])

#other way
data[data[:,1]>90]

[92]


array([[19, 92, 88]])

In [109]:
#Increase Math marks of all students by 5.
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [110]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [111]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [112]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:], axis = 0)

array([86.6, 83.2])

In [113]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [121]:
#Replace all Science marks < 75 with 0.
science_marks = data[:, 2] < 75
science_marks

array([False, False, False,  True, False])

In [122]:
data[science_marks, 2] = 0

In [123]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])